version: '3'
services:
  web:
    image: nginx
    volumes:
      - ./ops/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    ports:
      - "80:80"
    restart: always
    depends_on:
      - php

  php:
    build: ops/php
    restart: always
    volumes:
      - ./ops/php/conf/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./ops/php/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./app:/var/www/html
    depends_on:
      - db
      - redis
  db:
    image: postgres:10.1
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./ops/postgres/:/docker-entrypoint-initdb.d/

  redis:
    image: "redis:alpine"
    command: redis-server --port 6388 --requirepass ${REDIS_PASS}
    ports:
      - "6388:6388"
    volumes:
      - ./ops/redis/:/usr/local/etc/redis/
    environment:
      - REDIS_REPLICATION_MODE=${REDIS_REPLICATION_MODE}